name: Test API Access from GitHub Actions

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Make API Request
        run: |
          curl "https://actions.ctf.cert.unlp.edu.ar/"
